INPUT_DIR_KMERS: '../data/rodriguez_matrinez_elife_10bp_data/'
INTERIM_DIR: 'interim'
OUTPUT_DIR: 'output'
LOG_DIR: 'logs'

KMER_NAMES: [
    'ATF2_20N_lib5', 'ATF3_20N_lib5', 'ATF3_CEBPA_20N_lib6', 'ATF3_CEBPG_20N_lib1',
    'ATF3rep2_20N_lib2', 'ATF4_20N_lib5', 'ATF4_CEBPA_20N_lib1', 'ATF4_CEBPG_20N_lib1',
    'ATF4rep2_20N_lib2', 'ATF5_ATF6B_20N_lib10', 'ATF5_BATF2_20N_lib4', 'ATF5_BATF3_20N_lib4',
    'ATF5_BATF_20N_lib9', 'ATF5_CEBPA_20N_lib4', 'ATF5_CEBPE_20N_lib9', 'ATF5_CEBPG_20N_lib4',
    'ATF5_CREB3L1_20N_lib10', 'ATF5_CREB3L3_20N_lib10', 'ATF5_CREBZF_20N_lib4', 'ATF5_FOS_20N_lib4',
    'ATF5_JUNB_20N_lib9', 'ATF5_JUN_20N_lib4', 'ATF6B_20N_lib5', 'ATF6_20N_lib5',
    'BATF2_ATF3_20N_lib6', 'BATF2_ATF4_20N_lib1', 'BATF2_JUN_20N_lib4', 'BATF3_20N_lib5',
    'BATF3_ATF3_20N_lib7', 'BATF3_ATF3rep2_20N_lib6', 'BATF3_ATF4_20N_lib7', 'BATF3_CEBPA_20N_lib7',
    'BATF3_CEBPG_20N_lib7', 'BATF3_NFIL3_20N_lib7', 'BATF_ATF3_20N_lib6', 'BATF_CEBPA_20N_lib9',
    'BATF_CEBPE_20N_lib9', 'BATF_CEBPG_20N_lib9', 'BATF_HLF_20N_lib9', 'BATF_NFIL3_20N_lib9',
    'CEBPA_20N_lib5', 'CEBPB_JR50_007', 'CEBPE_ATF3_20N_lib6', 'CREB1_20N_lib5',
    'CREB3L1_20N_lib4', 'CREB3L1rep2_20N_lib2', 'CREB3_20N_lib5', 'DBP_20N_lib4',
    'DDIT3_CEBPG_20N_lib1', 'FOSL1_20N_lib9', 'FOSL1_ATF3_20N_lib6', 'FOSL1_BATF3_20N_lib9',
    'FOSL1_CEBPA_20N_lib9', 'FOSL1_CEBPE_20N_lib9', 'FOSL1_CEBPG_20N_lib9', 'FOSL1_JUN_20N_lib9',
    'FOSL1_NFE2_20N_lib9', 'FOS_ATF2_20N_lib1', 'FOS_ATF3_20N_lib6', 'FOS_ATF4_20N_lib4',
    'FOS_BATF2_20N_lib9', 'FOS_BATF3_20N_lib9', 'FOS_BATF_20N_lib9', 'FOS_CEBPE_20N_lib9',
    'FOS_CEBPG_20N_lib6', 'FOS_CREB3L3_20N_lib10', 'FOS_CREB3_20N_lib9', 'FOS_DBP_20N_lib9',
    'FOS_FOSL1_20N_lib9', 'FOS_JUN_20N_lib1', 'FOS_MAFB_20N_lib6', 'FOS_NFE2L1_20N_lib10',
    'FOS_NFE2_20N_lib10', 'HLF_20N_lib4', 'JUNB_ATF2_20N_lib9', 'JUNB_ATF3_20N_lib6',
    'JUNB_ATF4_20N_lib9', 'JUNB_BATF2_20N_lib9', 'JUNB_BATF3_20N_lib9', 'JUNB_BATF_20N_lib9',
    'JUNB_CEBPA_20N_lib9', 'JUNB_CEBPE_20N_lib9', 'JUNB_CEBPG_20N_lib9', 'JUNB_CREBZF_20N_lib9',
    'JUNB_DBP_20N_lib9', 'JUNB_FOSL1_20N_lib9', 'JUNB_FOS_20N_lib9', 'JUNB_HLF_20N_lib9',
    'JUNB_JUN_20N_lib9', 'JUNB_NFE2L1_20N_lib9', 'JUNB_NFE2_20N_lib9', 'JUN_20N_lib4',
    'JUN_ATF3_20N_lib1', 'JUN_CEBPA_20N_lib6', 'JUN_CEBPG_20N_lib4', 'MAFB_20N_lib3',
    'MAFB_ATF4_20N_lib8', 'MAFB_ATF5_20N_lib8', 'MAFB_FOSL1_20N_lib8', 'MAFG_20N_lib3',
    'NFE2L1_20N_lib4', 'NFE2L1_MAFG_20N_lib4', 'NFE2L1rep2_20N_lib3', 'NFE2L2_20N_lib2',
    'NFE2_20N_lib4', 'NFE2_MAFG_20N_lib4', 'NFE2rep2_20N_lib3', 'NFIL3_20N_lib2',
    'NFIL3rep2R01_335'
]

# How many best kmers to use to make MEME motif
N_KMERS_FOR_MEME: 1000
