configfile: 'config.yaml'

import pathlib

DIR_KMER_INPUT = pathlib.Path(config['INPUT_DIR_KMERS'])
DIR_INTERIM = pathlib.Path(config['INTERIM_DIR'])
DIR_OUTPUT = pathlib.Path(config['OUTPUT_DIR'])
DIR_LOG = pathlib.Path(config['LOG_DIR'])

KMERS = config['KMER_NAMES']


include: 'preprocessing/preprocessing.smk'
include: 'genomic/sequences.smk'
include: 'genomic/kmer_genomic_files.smk'

TARGETS = []
TARGETS.append(DIR_OUTPUT / 'kmer_z_score_dataframe.h5')

# Uncomment this if you need the bigwigs
# TARGETS.extend([DIR_OUTPUT / 'bw' / 'hg38' / f'{kmer_name}.ranks.bw' for kmer_name in KMERS])

TARGETS.extend([DIR_OUTPUT / 'bed' / 'hg38' / f'{kmer_name}.kmers.bed.gz' for kmer_name in KMERS])

rule all:
    input: TARGETS
